# Site settings
title: Góp nhặt cát đá
author:
  name: 0ld Camel
  email: 0ldcamel502@gmail.com
description: "Góp nhặt bài viết từ FaceBook Group."

# Build settings
remote_theme: jekyll/minima

#social_links:
  #  - title: Minima Theme repository at GitHub
  #    icon: github
  #    url: "https://github.com/jekyll/minima"
  #  - title: Jekyll at X (formerly Twitter)
  #    icon: x-twitter
  #    url: "https://x.com/jekyllrb"
